name: ci

on:
  push:
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build (CMake)
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release -- -j
      - name: Test (ctest)
        run: ctest --test-dir build --output-on-failure
      - name: Build (Make)
        run: |
          make
          make test
